name: Esto es una demo
on: [push]

jobs:
  archetype:
    runs-on: ubuntu-latest
    outputs:
      pom_exists: ${{ steps.check-pom.outputs.exists }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Comprobar si existe pom.xml
        id: check-pom
        run: |
          if [ test -e ./pom.xml ]; then
            echo "El archivo pom.xml existe en el repositorio."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "El archivo pom.xml no existe en el repositorio."
            echo "exists=false" >> $GITHUB_ENV
            exit 1 # Falla el trabajo si no existe

  build:
    runs-on: ubuntu-latest
    needs: archetype
    if: ${{ needs.acrchetype.outputs.pom_exists == 'true' }}
    steps:

      - name: Checkout del repositorio
        uses: actions/checkout@v3


      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'


      - name: Build con Maven
        run: mvn clean install

  code-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout del repositorio
        uses: actions/checkout@v3


      - name: Ejecutar pruebas y generar cobertura
        run: mvn clean verify

