name: Esto es una demo
on: [push]

jobs:
  archetype:
    runs-on: ubuntu-latest
    outputs:
      pom_exists: ${{ steps.check-pom.outputs.exists }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Comprobar si existe pom.xml
        id: check-pom
        run: |
          if [ ! -f pom.xml ]; then
            echo "Error: pom.xml not found."
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: archetype
    if: ${{ needs.acrchetype.outputs.pom_exists == 'true' }}
    steps:

      - name: Checkout del repositorio
        uses: actions/checkout@v4


      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'


      - name: Build con Maven
        run: mvn clean install

  code-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout del repositorio
        uses: actions/checkout@v4


      - name: Ejecutar pruebas y generar cobertura
        run: mvn clean verify

